### ISSUE TITLE
Functionality

### ISSUE THREAD

**Issue by karalistony** [karalistony/Temperature-Converter-stl#1]
##TODO

 - [ ] Give user ability to continue to input values until they wish to stop.
 - [ ] Store data after each conversion (ie array/ class)
 - [ ] Make data available to user by inputting p(for example)
